import { Inter } from "next/font/google";
import "./globals.css";

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Button } from "@/components/ui/button";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="border border-red-700">
        <ClerkProvider>
            <body>
              <SignedOut>
                <SignInButton />
              </SignedOut>
              <SignedIn>
               <Button>SignedIn</Button>
              </SignedIn>
              {children}
            </body>
        </ClerkProvider>
      </body>
    </html>
  );
}
